typedef struct _Points {
	char *paper;
	int points;
} Points;
typedef enum { CSE, IT, ECE, MECH, EEE, EI } Department;
typedef enum { one,two,three,four,five,six,seven,eight } Semester;

Points
CSE_2[] = { 
	{ "Technical English II", 4 },
	{ "Mathematics II", 4 },
	{ "Engineering Physics II", 3 },
	{ "Engineering Chemistry II", 3 },
	{ "Electric Circuits and Electron Devices", 4 },
	{ "Basic Civil and Mechanical Engineering", 4 },
	{ "Computer Practice LAB II", 2 },
	{ "Physics and Chemisty LAB ", 2 },
	{ "Circuits and Devices LAB", 2 },
},
CSE_3[] = { 
	{ "Transforms and Partial Differential Equations", 4 },
	{ "Data Structures", 3 },
	{ "Digital Principles and Systems Design", 4 },
	{ "Object Oriented Programming", 3 },
	{ "Analog and Digital Communication", 4 },
	{ "Environmental Science and Engineering", 3 },
	{ "Digital Lab", 2 },
	{ "Data Structures Lab", 2 },
	{ "Object Oriented Programming Lab", 2 },
},
CSE_4[] = { 
	{ "Probability and Queueing Theory", 4 },
	{ "Design and Analysis of Algorithms", 4 },
	{ "Microprocessors and Microcontrollers", 3 },
	{ "Computer Organization and Architecture", 3 },
	{ "Operating Systems", 3 },
	{ "Database Management Systems", 3 },
	{ "Operating Systems Lab", 2 },
	{ "Data Base Management Systems Lab", 2 },
	{ "Microprocessors Lab", 2 },
},
CSE_5[] = { 
	{ "Software Engineering", 3 },
	{ "Discrete Mathematics", 4 },
	{ "Computer Networks", 3 },
	{ "Theory of Computation", 4 },
	{ "System Software", 4 },
	{ "Programming Paradigms", 3 },
	{ "Network Lab", 2 },
	{ "System Software Lab", 2 },
	{ "Java Lab", 2 },
},
CSE_6[] = { 
	{ "Artificial Intelligence", 3 },
	{ "Principles of Compiler Design", 4 },
	{ "Object Oriented Analysis and Design", 3 },
	{ "Advanced Computer Architecture", 3 },
	{ "Elective  I", 3 },
	{ "Elective  II", 3 },
	{ "Object Oriented Analysis and Design Lab", 2 },
	{ "Communication Skills Lab", 2 },
	{ "Internet Programming Lab", 2 },
},
CSE_7[] = { 
	{ "Engineering Economics & Financial Accounting", 3 },
	{ "Computer Graphics", 3 },
	{ "Mobile and Pervasive Computing", 3 },
	{ "Digital Signal Processing", 3 },
	{ "Elective III", 3 },
	{ "Elective IV", 3 },
	{ "Computer Graphics Lab", 2 },
	{ "Open Source Lab", 2 },
},
CSE_1[] = { 
	{ "Technical English I", 4 },
	{ "Mathematics I", 4 },
	{ "Engineering Physics I", 3 },
	{ "Engineering Chemistry I", 3 },
	{ "Engineering Graphics", 5 },
	{ "Fundamentals of Computing and Programming ", 3 },
	{ "Computer Practice  LAB I", 2 },
	{ "Engineering Practice  LAB", 2 },
},
CSE_8[] = { 
	{ "Elective IV", 3 },
	{ "Elective V", 3 },
	{ "Project Work", 6 },
},
IT_2[] = { 
	{ "Technical English II", 4 },
	{ "Mathematics II", 4 },
	{ "Engineering Physics II", 3 },
	{ "Engineering Chemistry II", 3 },
	{ "Electric Circuits and Electron Devices", 4 },
	{ "Basic Civil and Mechanical Engineering", 4 },
	{ "Computer Practice LAB II", 2 },
	{ "Physics and Chemisty LAB ", 2 },
	{ "Circuits and Devices LAB", 2 },
},
IT_3[] = { 
	{ "Transforms and Partial Differential Equations", 4 },
	{ "Digital Principles and Systems Design", 4 },
	{ "Object Oriented Programming", 3 },
	{ "Data Structures and Algorithms", 3 },
	{ "Principles of Communication", 4 },
	{ "Environmental Science and Engineering", 3 },
	{ "Digital Lab", 2 },
	{ "Data Structures and Algorithms Lab", 2 },
	{ "Object Oriented Programming Lab", 2 },
},
IT_4[] = { 
	{ "Probability and Queueing Theory", 4 },
	{ "Database Management Systems", 3 },
	{ "Microprocessors and Microcontrollers", 3 },
	{ "Computer Organization and Architecture", 3 },
	{ "Operating Systems", 3 },
	{ "Software Engineering and Quality Assurance", 3 },
	{ "Operating Systems Lab", 2 },
	{ "Data Base Management Systems Lab", 2 },
	{ "Microprocessors Lab", 2 },
},
IT_5[] = { 
	{ "Java Programming", 3 },
	{ "Engineering Economics & Financial Accounting", 3 },
	{ "System Software", 4 },
	{ "Computer Networks", 3 },
	{ "Digital Signal Processing", 3 },
	{ "Information Theory and Coding", 3 },
	{ "System Software Lab", 2 },
	{ "Java Programming Lab", 2 },
	{ "Communication Skills Lab", 2 },
},
IT_6[] = { 
	{ "Network Programming and Management", 3 },
	{ "Object Oriented Analysis and Design", 3 },
	{ "Cryptography and Network Security", 3 },
	{ "Web Technology", 3 },
	{ "Embedded Systems", 3 },
	{ "Elective I", 3 },
	{ "Web Technology Lab", 2 },
	{ "Object Oriented Analysis and Design Lab", 2 },
	{ "Network Lab", 2 },
},
IT_7[] = { 
	{ "Service Oriented Architecture", 3 },
	{ "Mobile Communication", 3 },
	{ "Computer Graphics", 3 },
	{ "Software Project Management", 3 },
	{ "Elective II", 3 },
	{ "Elective III", 3 },
	{ "Service Oriented Architecture Lab", 2 },
	{ "Computer Graphics Lab", 2 },
},
IT_1[] = { 
	{ "Technical English I", 4 },
	{ "Mathematics I", 4 },
	{ "Engineering Physics I", 3 },
	{ "Engineering Chemistry I", 3 },
	{ "Engineering Graphics", 5 },
	{ "Fundamentals of Computing and Programming ", 3 },
	{ "Computer Practice  LAB I", 2 },
	{ "Engineering Practice  LAB", 2 },
},
IT_8[] = { 
	{ "Elective IV", 3 },
	{ "Elective V", 3 },
	{ "Project Work", 6 },
},
ECE_2[] = { 
	{ "Technical English II", 4 },
	{ "Mathematics II", 4 },
	{ "Engineering Physics II", 3 },
	{ "Engineering Chemistry II", 3 },
	{ "Electric Circuits and Electron Devices", 4 },
	{ "Basic Civil and Mechanical Engineering", 4 },
	{ "Computer Practice LAB II", 2 },
	{ "Physics and Chemisty LAB ", 2 },
	{ "Circuits and Devices LAB", 2 },
},
ECE_3[] = { 
	{ "Transforms and Partial Differential Equations", 4 },
	{ "Electrical Engineering", 3 },
	{ "Data Structures and Object Oriented Programming in C++", 3 },
	{ "Digital Electronics", 4 },
	{ "Signals and systems", 4 },
	{ "Electronic Circuits I", 4 },
	{ "Digital Electronics Lab", 2 },
	{ "Electronic Circuits Lab I", 2 },
	{ "Data structures and Object Oriented Programming Lab", 2 },
},
ECE_4[] = { 
	{ "Probability and Random Processes", 4 },
	{ "Electronic Circuits II", 4 },
	{ "Communication Theory", 4 },
	{ "Electromagnetic Fields", 4 },
	{ "Linear Integrated Circuits", 3 },
	{ "Control Systems", 3 },
	{ "Electronics circuits II and simulation Lab", 2 },
	{ "Linear Integrated Circuit Lab", 2 },
	{ "Electrical Engineering and Control System Lab", 2 },
},
ECE_5[] = { 
	{ "Digital Communication", 3 },
	{ "Digital Signal Processing", 4 },
	{ "Computer Architecture and Organization", 3 },
	{ "Transmission Lines and Wave guides", 4 },
	{ "Environmental Science and Engineering", 3 },
	{ "Microprocessors and Microcontrollers", 4 },
	{ "Digital Signal Processing Lab", 2 },
	{ "Communication System Lab", 2 },
	{ "Microprocessors and Microcontrollers Lab", 2 },
},
ECE_6[] = { 
	{ "Principles of Management", 3 },
	{ "Measurements and Instrumentation", 3 },
	{ "Computer Networks", 3 },
	{ "Antenna and Wave Propagation", 4 },
	{ "VLSI Design", 3 },
	{ "Elective I", 3 },
	{ "Computer Networks Lab", 2 },
	{ "VLSI Design Lab", 2 },
	{ "Communication Skills Lab", 2 },
},
ECE_7[] = { 
	{ "Wireless Communication", 3 },
	{ "Optical Communication and Networks", 3 },
	{ "RF and Microwave Engineering", 3 },
	{ "Elective II", 3 },
	{ "Elective III", 3 },
	{ "Elective IV", 3 },
	{ "Electronics System Design Lab", 2 },
	{ "Optical & Microwave Lab", 2 },
},
ECE_1[] = { 
	{ "Technical English I", 4 },
	{ "Mathematics I", 4 },
	{ "Engineering Physics I", 3 },
	{ "Engineering Chemistry I", 3 },
	{ "Engineering Graphics", 5 },
	{ "Fundamentals of Computing and Programming ", 3 },
	{ "Computer Practice  LAB I", 2 },
	{ "Engineering Practice  LAB", 2 },
},
ECE_8[] = { 
	{ "Elective IV", 3 },
	{ "Elective V", 3 },
	{ "Project Work", 6 },
},
MECH_2[] = { 
	{ "Technical English II", 4 },
	{ "Mathematics II", 4 },
	{ "Engineering Physics II", 3 },
	{ "Engineering Chemistry II", 3 },
	{ "Engineering Mechanics", 4 },
	{ "Basic Electrical and Electronics Engineering", 4 },
	{ "Computer Practice  LAB II", 2 },
	{ "Physics and Chemisty LAB ", 2 },
	{ "Computer Aided Drafting and Modeling LAB", 2 },
},
MECH_3[] = { 
	{ "Transforms and Partial Differential Equations", 4 },
	{ "Manufacturing Technology  I", 3 },
	{ "Engineering Thermodynamics", 4 },
	{ "Kinematics of Machinery", 4 },
	{ "Fluid Mechanics and Machinery", 4 },
	{ "Electrical Drives and Control", 3 },
	{ "Manufacturing Technology Lab  I", 2 },
	{ "Fluid Mechanics and Machinery Lab", 2 },
	{ "Electrical Engineering Lab", 2 },
},
MECH_4[] = { 
	{ "Statistics and Numerical Methods", 4 },
	{ "Heat and Mass Transfer", 4 },
	{ "Manufacturing Technology", 3 },
	{ "Engineering Materials and Metallurgy", 3 },
	{ "Strength of Materials", 4 },
	{ "Electronics and Microprocessors", 3 },
	{ "Manufacturing Technology Lab", 2 },
	{ "Strength of Materials Lab", 2 },
	{ "Computer Aided Machine Drawing Laboratory", 2 },
},
MECH_5[] = { 
	{ "Environmental Science and Engineering", 3 },
	{ "Database Management Systems", 4 },
	{ "Design of Machine Elements", 4 },
	{ "Management of Manufacturing System", 4 },
	{ "Measurements and Controls", 3 },
	{ "Applied Hydraulics and Pneumatics", 3 },
	{ "Dynamics Lab", 2 },
	{ "Metrology and Measurements Lab", 2 },
	{ "Computer Aided Machine Drawing Practice", 2 },
	{ "Database Management Systems Lab", 2 },
},
MECH_6[] = { 
	{ "Principles of Management", 3 },
	{ "Gas Dynamics and Jet Propulsion", 4 },
	{ "Design of Transmission Systems", 4 },
	{ "Automobile Engineering", 3 },
	{ "Finite Element Analysis", 4 },
	{ "Elective I", 3 },
	{ "Thermal Engineering Lab II", 2 },
	{ "Design & Fabrication Project", 2 },
	{ "Communication Skills Lab", 2 },
},
MECH_7[] = { 
	{ "Total Quality Management", 3 },
	{ "Mechatronics", 3 },
	{ "Computer Integrated Manufacturing", 3 },
	{ "Power Plant Engineering", 3 },
	{ "Elective II", 3 },
	{ "Elective III", 3 },
	{ "Computer Aided Simulation & Analysis Lab", 2 },
	{ "Mechatronics Lab", 2 },
},
MECH_8[] = { 
	{ "Engineering Economics and Cost Analysis", 3 },
	{ "Elective IV", 3 },
	{ "Elective V", 3 },
	{ "Comprehension", 1 },
	{ "Project Work", 6 },
},
MECH_1[] = { 
	{ "Technical English I", 4 },
	{ "Mathematics I", 4 },
	{ "Engineering Physics I", 3 },
	{ "Engineering Chemistry I", 3 },
	{ "Engineering Graphics", 5 },
	{ "Fundamentals of Computing and Programming ", 3 },
	{ "Computer Practice  LAB I", 2 },
	{ "Engineering Practice  LAB", 2 },
},
EEE_2[] = { 
	{ "Technical English II", 4 },
	{ "Mathematics II", 4 },
	{ "Engineering Physics II", 3 },
	{ "Engineering Chemistry II", 3 },
	{ "Circuit Theory", 4 },
	{ "Basic Civil and Mechanical Engineering", 4 },
	{ "Computer Practice LAB II", 2 },
	{ "Physics and Chemisty LAB ", 2 },
	{ "Electric Circuits LAB", 2 },
},
EEE_3[] = { 
	{ "Transforms and Partial Differential Equations", 4 },
	{ "Measurements & Instrumentation", 3 },
	{ "Electromagnetic Theory", 4 },
	{ "Environmental Science and Engineering", 3 },
	{ "Electronic Devices & Circuits", 3 },
	{ "Data Structures and Algorithms", 4 },
	{ "Electron Devices and Circuits Lab", 2 },
	{ "Data Structures and Algorithms Lab", 2 },
	{ "Measurements & Instrumentation Lab", 2 },
},
EEE_4[] = { 
	{ "Numerical Methods", 4 },
	{ "Electrical Machines  I", 4 },
	{ "Power Plant Engineering", 4 },
	{ "Control Systems", 4 },
	{ "Linear Integrated Circuits and Applications", 3 },
	{ "Digital Logic Circuits", 4 },
	{ "Control Systems Lab", 2 },
	{ "Linear and Digital Integrated Circuits Lab", 2 },
	{ "Electrical Machines Lab  I", 2 },
},
EEE_5[] = { 
	{ "Communication Engineering", 3 },
	{ "Digital Signal Processing", 4 },
	{ "Object Oriented Programming", 3 },
	{ "Power Electronics", 3 },
	{ "Electrical Machines II", 4 },
	{ "Transmission & Distribution", 4 },
	{ "Object Oriented Programming Lab", 2 },
	{ "Communication Skills Lab", 2 },
	{ "Power Electronics Lab", 2 },
	{ "Electrical Machines Lab II", 2 },
},
EEE_6[] = { 
	{ "Power System Analysis", 4 },
	{ "Solid State Drives", 3 },
	{ "High Voltage Engineering", 3 },
	{ "Microprocessors and Micro controller", 3 },
	{ "Design of Electrical Machines", 4 },
	{ "Computer Networks", 3 },
	{ "Elective I", 3 },
	{ "Microprocessor and Micro controller Lab", 2 },
	{ "Presentation Skills and Technical Seminar", 1 },
},
EEE_7[] = { 
	{ "Power System Operation and Control", 3 },
	{ "Protection & Switchgear", 3 },
	{ "Special Electrical Machines", 3 },
	{ "Principles of Management", 3 },
	{ "Operating Systems", 3 },
	{ "Elective II", 3 },
	{ "Power System Simulation Lab", 2 },
	{ "Comprehension", 1 },
},
EEE_1[] = { 
	{ "Technical English I", 4 },
	{ "Mathematics I", 4 },
	{ "Engineering Physics I", 3 },
	{ "Engineering Chemistry I", 3 },
	{ "Engineering Graphics", 5 },
	{ "Fundamentals of Computing and Programming ", 3 },
	{ "Computer Practice  LAB I", 2 },
	{ "Engineering Practice  LAB", 2 },
},
EEE_8[] = { 
	{ "Elective IV", 3 },
	{ "Elective V", 3 },
	{ "Project Work", 6 },
},
EI_2[] = { 
	{ "Technical English II", 4 },
	{ "Mathematics II", 4 },
	{ "Engineering Physics II", 3 },
	{ "Engineering Chemistry II", 3 },
	{ "Circuit Theory", 4 },
	{ "Basic Civil and Mechanical Engineering", 4 },
	{ "Computer Practice LAB II", 2 },
	{ "Physics and Chemisty LAB ", 2 },
	{ "Electric Circuits LAB", 2 },
},
EI_3[] = { 
	{ "Transforms and Partial Differential Equations", 4 },
	{ "Environmental Science and Engineering", 3 },
	{ "Electrical Machines", 4 },
	{ "Electronic Devices and Circuits", 3 },
	{ "Data Structures and Algorithms", 4 },
	{ "Electrical Measurements", 4 },
	{ "Electron Devices and Circuits Lab", 2 },
	{ "Data Structures and Algorithms Lab", 2 },
	{ "Electrical Machines Lab", 2 },
},
EI_4[] = { 
	{ "Control Systems", 4 },
	{ "Industrial Instrumentation I", 3 },
	{ "Transducer Engineering", 3 },
	{ "Digital logic Circuits", 4 },
	{ "Linear Integrated Circuits and Applications", 3 },
	{ "Applied Thermodynamics", 4 },
	{ "Transducers and Measurements Lab", 2 },
	{ "Thermodynamics Lab", 2 },
	{ "Linear and Digital Integrated circuits Lab", 2 },
},
EI_5[] = { 
	{ "Microprocessor and  Microcontroller", 3 },
	{ "Communication Engineering", 3 },
	{ "Object Oriented Programming", 3 },
	{ "Industrial Electronics", 3 },
	{ "Analytical Instruments", 3 },
	{ "Industrial Instrumentation II", 3 },
	{ "Microprocessor and Microcontroller Lab", 2 },
	{ "Object Oriented Programming Lab", 2 },
	{ "Communication Skills Lab", 2 },
	{ "Industrial Instrumentation Lab", 2 },
},
EI_6[] = { 
	{ "Modern Electronic Instrumentation", 3 },
	{ "Process Control", 4 },
	{ "Digital System Design", 3 },
	{ "Digital Signal Processing", 4 },
	{ "Embedded System", 3 },
	{ "Biomedical Instrumentation", 3 },
	{ "Communication and DSP Lab", 2 },
	{ "Process Control System Lab", 2 },
	{ "Virtual Instrumentation Lab", 2 },
},
EI_7[] = { 
	{ "Industrial Data Networks", 3 },
	{ "Logic and Distributed Control System", 3 },
	{ "VLSI Design", 3 },
	{ "Fibre Optics and Laser Instruments", 3 },
	{ "Elective I", 3 },
	{ "Elective II", 3 },
	{ "VLSI Lab", 2 },
	{ "Instrumentation System Design Lab", 2 },
	{ "Comprehension", 2 },
},
EI_8[] = { 
	{ "Principles of Management", 3 },
	{ "Elective III", 3 },
	{ "Elective IV", 3 },
	{ "Project Work", 6 },
},
EI_1[] = { 
	{ "Technical English I", 4 },
	{ "Mathematics I", 4 },
	{ "Engineering Physics I", 3 },
	{ "Engineering Chemistry I", 3 },
	{ "Engineering Graphics", 5 },
	{ "Fundamentals of Computing and Programming ", 3 },
	{ "Computer Practice  LAB I", 2 },
	{ "Engineering Practice  LAB", 2 },
};

	Points 
	*cse[] = {	CSE_1, CSE_2, CSE_3, CSE_4, CSE_5, CSE_6, CSE_7, CSE_8 ,},
	*it[] =  {	IT_1, IT_2, IT_3, IT_4, IT_5, IT_6, IT_7, IT_8 ,},
	*ece[] = {	ECE_1, ECE_2, ECE_3, ECE_4, ECE_5, ECE_6, ECE_7, ECE_8, }, 
	*mech[] = {	MECH_1, MECH_2, MECH_3, MECH_4, MECH_5, MECH_6, MECH_7, MECH_8,  },
	*eee[] = {	EEE_1, EEE_2, EEE_3, EEE_4, EEE_5, EEE_6, EEE_7, EEE_8,  },
	*ei[] = {	EI_1, EI_2, EI_3, EI_4, EI_5, EI_6, EI_7, EI_8 };

	Points **list[] = {cse,it,ece,mech,eee,ei};
	

	int no_of_papers[][8] = { 

		8, 9, 9, 9, 9, 9, 8, 3,
		8, 9, 9, 9, 9, 9, 8, 3,
		8, 9, 9, 9, 9, 9, 8, 3,
		8, 9, 9, 9, 10, 9, 8, 4,
		8, 9, 9, 9, 10, 9, 8, 3,
		8, 9, 9, 9, 10, 9, 9, 4,

	};

	char *departments[] = {
		"Computer Science and Engineering",
		"Information Technology",
		"Electronics and Communication Engineering",
		"Mechanical Engineering",
		"Electrical and Electronics Engineering",
		"Electronics and Instrumentation Engineering"
	};

